# Generated by Django 3.0.5 on 2020-04-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200410_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='things_to_do',
            new_name='eventst',
        ),
    ]
