# Generated by Django 3.0.5 on 2020-04-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_trip_budget12'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.URLField(default='https://globalcenters.columbia.edu/sites/default/files/styles/cu_crop/public/content/istanbul/visiting%20city/istanbul%20002.jpg?h=eba642ff&itok=rOu6u0xq'),
        ),
    ]
