# Generated by Django 3.0.5 on 2020-04-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200410_2211'),
        ('main_app', '0004_auto_20200410_2209'),
    ]

    operations = [
    ]
